networks:
  default:
    name: wagrandprix
services:
  agx:
    build:
      args:
        APT_DEPENDENCIES: bash zsh vim git git-lfs python3-pip python3-tk
        CONTAINERNAME: agx
        PIP_REQUIREMENTS: wa_simulator pandas matplotlib python-can psutil twisted
          numpy>=1.19 opencv-python tornado black Pillow canlib
        PROJECT: wagrandprix
        USER_GID: '1000'
        USER_GROUPS: dialout video
        USER_UID: '1000'
      context: ./
      dockerfile: ./containers/dev/dev.dockerfile
      network: host
    container_name: wagrandprix-dev
    environment:
      DISPLAY: vnc:0.0
      NVIDIA_DRIVER_CAPABILITIES: all
      NVIDIA_VISIBLE_DEVICES: all
    hostname: wagrandprix-agx
    image: atk/wagrandprix:agx
    networks:
      default: null
    ports:
    - mode: ingress
      protocol: tcp
      published: 8888
      target: 8888
    privileged: true
    runtime: nvidia
    tty: true
    volumes:
    - bind:
        create_host_path: true
      source: /home/wa-ecu/waGrandPrix
      target: /home/wagrandprix/wagrandprix
      type: bind
    working_dir: /home/wagrandprix/wagrandprix/workspace
