networks:
  default:
    name: wagrandprix
services:
  dev:
    build:
      args:
        APT_DEPENDENCIES: bash zsh vim git git-lfs python3-pip python3-tk
        PIP_REQUIREMENTS: wa_simulator pandas matplotlib python-can psutil twisted
          numpy>=1.19 opencv-python tornado black Pillow
        PROJECT: wagrandprix
        USER_GID: '1000'
        USER_GROUPS: dialout video
        USER_UID: '1000'
      context: /home/unijay/waGrandPrix
      dockerfile: ./containers/dev/dev.dockerfile
      network: host
    container_name: wagrandprix-dev
    environment:
      DISPLAY: vnc:0.0
      NVIDIA_DRIVER_CAPABILITIES: all
      NVIDIA_VISIBLE_DEVICES: all
    hostname: wagrandprix-dev
    image: atk/wagrandprix:dev
    networks:
      default: null
    ports:
    - mode: ingress
      protocol: tcp
      published: 8888
      target: 8888
    tty: true
    volumes:
    - bind:
        create_host_path: true
      source: /home/unijay/waGrandPrix
      target: /home/wagrandprix/wagrandprix
      type: bind
    working_dir: /home/wagrandprix/wagrandprix/workspace
  vnc:
    build:
      args:
        RUN_FLUXBOX: 'yes'
        RUN_XTERM: 'yes'
        VNC_PASSWORD: wagrandprix
      context: /home/unijay/waGrandPrix/containers/vnc
      dockerfile: ./vnc.dockerfile
      network: host
    container_name: wagrandprix-vnc
    environment:
      RUN_FLUXBOX: 'true'
      RUN_XTERM: 'false'
    hostname: wagrandprix-vnc
    image: atk/wagrandprix:vnc
    networks:
      default: null
    ports:
    - mode: ingress
      protocol: tcp
      published: 8080
      target: 8080
    - mode: ingress
      protocol: tcp
      published: 5900
      target: 5900
