project: wagrandprix
default_services: 
  - dev
  - vnc
services:
  dev:
    build:
      args:
        APT_DEPENDENCIES: "bash zsh vim git git-lfs python3-pip python3-tk"
        PIP_REQUIREMENTS: "wa_simulator pandas matplotlib python-can psutil twisted numpy>=1.19 opencv-python tornado black Pillow"
    ports:
      - "8888:8888"
  vnc:
    build:
      args:
        VNC_PASSWORD: ""
  wasim:
    image: "wiscauto/@{project}:wasim"
    hostname: "@{project}-wasim"
    container_name: "@{project}-wasim"
    build:
      context: ./docker/wasim
      dockerfile: ./wasim.dockerfile
      network: "host"
      args:
        USERNAME: "@{project}"
        USER_UID: "@{uid}"
        USER_GID: "@{gid}"
        APT_DEPENDENCIES: "wget bash python3-tk"
        CONDA_CHANNELS: ""
        CONDA_DEPENDENCIES: ""
        PIP_DEPENDENCIES: "wa_simulator"
    working_dir: "/home/@{container_username}/@{project}/sim/wasim"
    environment:
      DISPLAY: "vnc:0.0"
    volumes: 
      - "@{project_root}:/home/@{container_username}/@{project}"
    tty: true
