project: wagrandprix
default_services: 
  - dev
  - vnc
services:
  dev:
    build:
      args:
        APT_DEPENDENCIES: "bash zsh vim git git-lfs python3-pip python3-tk"
        PIP_REQUIREMENTS: "wa_simulator pandas matplotlib python-can, psutil, twisted, numpy>=1.19 opencv-python tornado black Pillow"
    ports:
      - "8888:8888"
  vnc:
    build:
      args:
        VNC_PASSWORD: ""
