project: wagrandprix
dev:
  scripts: docker/dev/scripts
  ports:
    - "8888:8888"
  apt-dependencies: [bash, zsh, vim, git, git-lfs, python3-pip, python3-tk]
  pip-requirements: [wa_simulator, pandas, matplotlib, python-can, psutil, black, twisted, numpy>=1.19, opencv-python, tornado, black, Pillow]
vnc:
  vnc_password: ""
