version: "3.9"
services:
  wagrandprix-dev:
    container_name: 'wagrandprix-dev'
    hostname: 'wagrandprix-dev'
    image: 'wiscauto/wagrandprix:develop'
    build:
      context: ./
      dockerfile: ./docker/dev.dockerfile
      network: host
    ports:
      - "8888:8888"
    volumes:
      - .:/root/waGrandPrix
    tty: true
    working_dir: /root/
    networks:
      wa:
        ipv4_address: "172.20.0.2"
  wagrandprix-prod:
    container_name: 'wagrandprix-prod'
    hostname: 'wagrandprix-prod'
    image: 'wiscauto/wagrandprix:prod'
    build:
      context: ./
      dockerfile: ./docker/prod.dockerfile
      network: host
    ports:
      - "8888:8888"
    volumes:
      - .:/root/waGrandPrix
    tty: true
    working_dir: /root/
    networks:
      wa:
        ipv4_address: "172.20.0.2"
networks:
  wa:
    external: true
