version: "3.9"
services:
  wagrandprix-dev:
    hostname: 'wagrandprix-dev'
    build:
      context: ./
      dockerfile: ./docker/dev.dockerfile
      args:
        USERSHELL: zsh
      network: host
    ports:
      - "8888:8888"
    volumes:
      - .:/root/waGrandPrix
      - ~/.ssh/:/root/.ssh/
      - ~/.gitconfig:/root/.gitconfig
    tty: true
    working_dir: /root/
    environment:
      DISPLAY: "host.docker.internal:0" 
