version: "3.9"
services:
  wagrandprix-dev:
    container_name: 'wagrandprix-dev'
    hostname: 'wagrandprix-dev'
    build:
      context: ./
      dockerfile: ./docker/dev.dockerfile
      args:
        USERSHELL: zsh
      network: host
    ports:
      - "8888:8888"
    volumes:
      - .:/root/waGrandPrix
    tty: true
    working_dir: /root/
    networks:
      - wa
networks:
  wa:
    external: true
    name: wa 
    ipam:
      config:
        - subnet: "172.20.0.0/24"
